---
collections:
  - name: ansible.windows 
    version: 1.9.0
  - name: amazon.aws
    version: 3.1.1
  - name: ansible.controller 
    version: 4.1.1
  - name: containers.podman 
    version: 1.9.3
  - name: community.general 
    version: 4.6.1
  - name: community.crypto
    version: 2.2.4
  - name: ansible.posix 
    version: 1.3.0
  - name: community.aws
    version: 3.1.0
  - name: community.postgresql
    version: 2.1.2
  - name: community.crypto
    version: 2.2.4
  - name: redhat_cop.controller_configuration
    version: 2.1.4
  - name: redhat.insights 
    version: 1.0.7