---       
# - name: Install controller and hub 
#   hosts: localhost
#   connection: local sys
#   vars:
#     ansible_user: ec2-user
#   tasks:

#     - name: Controller Setup 
#       include_role: 
#         name: controller
#         tasks_from: setup.yml

- name: Copy signed certificate to Controller hosts 
  hosts: demo_controller
  vars:
    ansible_user: ec2-user 
  become: yes
  
  tasks:
    - name: Copy cert
      copy:
        src: generated_files/controller_chain 
        dest: /etc/tower/tower.cert
        group: awx
      register: copy_cert

    - name: Copy key 
      copy:
        src: "{{ acme_private_key_path }}"
        dest: /etc/tower/tower.key
        group: awx
      register: copy_key

    - name: restart nginx 
      systemd:
        name: nginx 
        state: restarted
      when: copy_cert is changed or copy_key is changed

- name: Copy signed certificates to Automation Hub hosts
  hosts: demo_hub 
  vars:
    ansible_user: ec2-user 
  become: yes

  tasks:
    - name: Copy cert
      copy:
        src: generated_files/hub_chain 
        dest: /etc/pulp/certs/pulp_webserver.crt
      register: copy_cert

    - name: Copy key 
      copy:
        src: "{{ acme_private_key_path }}"
        dest: /etc/pulp/certs/pulp_webserver.key
      register: copy_key

    - name: restart nginx 
      systemd:
        name: nginx 
        state: restarted
      when: copy_cert is changed or copy_key is changed