---
- name: Get list of instances for user as part of this demo 
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    filters:
      instance-state-name: running 
      # tag:business_domain_name: Red Hat 
      tag:demo: Ansible 
      tag:demo_core: false
  register: ec2 

- debug:
    msg: "{{ ec2 | community.general.json_query('instances[*].tags.server_name') | join('\n') }}"
    
- name: Update  Deprovision Template
  ansible.controller.job_template:
    name: "2. Deprovision"
    job_type: "run"
    inventory: AWS
    project: Demo Environment Tools
    playbook: "deprovision.yml"
    credentials: 
      - "Ansible Controller"
      - "AWS"
    survey_enabled: yes 
    survey_spec: | 
      {
        "name": "",
        "description": "",
        "spec": [
          {
              "question_name": "Select a server or servers to deprovision",
              "question_description": "",
              "required": true,
              "type": "multiselect",
              "variable": "survey_server_name",
              "min": null,
              "max": null,
              "default": "",
              "choices": "{{ ec2 | community.general.json_query('instances[*].tags.server_name') | join('\n') }}"
          }
        ]
      }
    state: "present"
    controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
    validate_certs: true