- name: Setup automation hub dns check for acme challenge 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ hub_challenge_record }}"
    type: TXT
    value: "{{ hub_challenge_value }}"
    ttl: 60
    wait: yes
    overwrite: yes
  when: hub_dns_challenge.challenge_data | length > 0

- name: Setup automation controller dns check for acme challenge 
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ controller_challenge_record }}"
    type: TXT
    value: "{{ controller_challenge_value }}"
    ttl: 60
    wait: yes
    overwrite: yes
  when: controller_dns_challenge.challenge_data | length > 0