---
controller_credentials:
  - credential_type: Machine
    organization: Default
    name: AWS Linux
    description: This credential can be used with any linux VM in your inventory source
    inputs:
      username: ec2-user
      ssh_key_data: "{{ private_key }}" # location of private key set in extra_vars.yml
  - credential_type: Machine
    organization: Default
    name: AWS Windows
    description: This credential can be used with any Windows VM in your inventory source
    inputs:
      username: Administrator
      password: "{{ admin_password }}"  ## Defaults to same password used to access Tower set in extra_vars.yml
      ssh_key_data: "{{ private_key }}"
      become_method: runas 
      become_username: Administrator 
      become_password: "{{ admin_password }}"
  - credential_type: Amazon Web Services
    organization: Default
    name: AWS 
    description: This credential can be used to automate AWS infrastructure and networking 
    inputs:
      username: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
      password: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"

  # This section will update existing credentials for the FQDN, instead of AWS utility URLs

  - credential_type: Container Registry 
    organization: Default 
    name: Automation Hub Container Registry 
    inputs:
      host: hub.{{ top_level_domain }}
      username: admin
      password: "{{ admin_password }}"
      