- name: Find AMI for Linux Host
  amazon.aws.ec2_ami_info:
    region: "{{ aws_region }}"
    owners: 309956199498
    filters:
      name: 'RHEL-8*HVM-*Hourly*'
      architecture: x86_64
  register: amis

- name: save ami for rhel node
  set_fact:
    node_ami_rhel: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}

- name: Provision EC2 Linux Instance 
  vars:
    query: subnets[?tags.env=='{{ server_env }}'] | [0].subnet_id
  amazon.aws.ec2_instance:
    state: started
    name: "{{ server_env }}-{{ server_name }}-{{ server_os }}"
    security_group: "{{ sec_info.security_groups[0].group_name }}"
    vpc_subnet_id: "{{ vpc_subnet_info | json_query(query) }}"
    image_id: "{{ node_ami_rhel.image_id }}"
    instance_type: "{{ aws_instance_type }}"
    key_name: "ansible-demo-key"
    tags: 
      group_name: "{{ group_name }}"
      server_name: "{{ server_name }}"
      server_env: "{{ server_env }}" 
      server_os: "{{ server_os }}"
      business_domain_name: "{{ top_level_domain }}"
      demo: Ansible 
    wait: yes
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: ec2